### ISSUE TITLE
Network Table- total packets vs packets Sent in interval

### ISSUE THREAD

**Issue by BradleyLamitie** [HarshaKota/MSCS-710L-Project#36]
Do we want to show how many total packets were sent in total or how many were sent since the last timestamp?

**Comment by HarshaKota** [comment]
That's a good question. The operating system keeps a rolling count of the total packets sent and received, but yes we can adjust and display only the number of packets during that period

**Comment by HarshaKota** [comment]
ad819109fb712ac0a321fd056e8f47c30e577322 fixes it.
