### ISSUE TITLE
Move Dropdown box and buttons to bottom?

### ISSUE THREAD

**Issue by BradleyLamitie** [HarshaKota/MSCS-710L-Project#44]
Should we move the buttons and selection box to the bottom of the window? This would follow what we have done in all other windows, and what the user would expect? (Principle of least astonishment)

**Comment by HarshaKota** [comment]
Oh, I never though of it that way.
I does look different than the rest, but since it actually is. The others are charts and this isn't may be that distinction can be carried over to the design.

Let's talk over this in the next meeting.

**Comment by BradleyLamitie** [comment]
Editing issue as per our discussion:
We decided that because static metrics are different in nature, the current UI can be different as well. Also, the current version gives the metrics in an easy to read form that would be impeded by having the bar at the bottom.
