### ISSUE TITLE
Power Table was created when run on Desktop

### ISSUE THREAD

**Issue by HarshaKota** [HarshaKota/MSCS-710L-Project#7]
Power table should not be created when in this situation

**Comment by BradleyLamitie** [comment]
Is this an issue? I think the professor mentioned that you can link a battery to a desktop. We could either not create the table, or in the UI we can display to the user that there wasn't a battery at that time so there's nothing to show. What do you think?

**Comment by HarshaKota** [comment]
True, but there's no way for the system to know if there's a power source attached to it. Laptops have sensors in the hardware that allows windows to talk to it and get the information. On desktops that's not possible, even if so there was something attached to the system, windows and OSHI wouldn't know about it.
If there is nothing we are going to save in that table we might as well just not create the table

**Comment by HarshaKota** [comment]
Recent Commit fixes the issue, the power table is no more created if there is no battery or if the battery percentage is returned as 0.0%

52868a88c6fcda9f5a0577fbca8a717bcea01a2d
