### ISSUE TITLE
Temparature values are scorching hot

### ISSUE THREAD

**Issue by HarshaKota** [HarshaKota/MSCS-710L-Project#8]
They can't possible be the correct values

**Comment by BradleyLamitie** [comment]
Have you been able to test this on your system?

**Comment by HarshaKota** [comment]
The values on my system seem to be stable and consistent. Could you pull the code to get any changes made, and run multiple times on your system, try to remove the database from the folder for the next run so we can have multiple database files with the temperature info. Do may be 5 runs .Send them over to me in Slack and text me when you do.

**Comment by HarshaKota** [comment]
I've run this a couple of times on a desktop and doesn't return and abnormal values for temperature. I think the update to the lastest OSHI fixed it. Will close this issue now.
